module.exports = {
  "com": [
    // 2005
    "Ottawa, Ontario",
    "Stratford, Ontario",
    // 2007
    "Ottawa, Ontario",
    "Toronto, Canada",
    // 2009
    "Ottawa, Ontario",
    "Toronto, Canada",
    "Ottawa, Ontario",
    "Kingston, Ontario",
    "Ottawa, Ontario",
    "Waterloo, Ontario",
    "Ottawa, Ontario",
    // September -> December 2009 (1A) - Village 1
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada", // Thanksgiving
    "Waterloo, Canada",
    "Hamilton, Canada", // ACM Regionals
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2010 (1B) - Velocity
    "Waterloo, Canada",
    // March -> August 2010 (TWG)
    "Toronto, Canada",
    // September -> December 2010 (2A) - Glenelm
    "Waterloo, Canada",
    "London, Canada", // Yuxuan's 19th
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Niagara Falls, Canada", // 2 yr anniv
    "Waterloo, Canada",
    "Ottawa, Canada",
    // January -> April 2011 (Kontagent)
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    // May -> August 2011 (2B) - Glenelm
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada", // mom's birthday
    "Waterloo, Canada",
    "Ottawa, Canada", // mom's retirement
    "Waterloo, Canada",
    "Ottawa, Canada", // G test
    "Waterloo, Canada",
    // September -> December 2011 (Facebook)
    "Ottawa, Canada",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2012 (3A) - Velocity
    "Toronto, Canada",
    "Waterloo, Canada",
    "Montreal, Canada", // CUSEC
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // May -> August 2013 (Khan Academy, Remote from Toronto)
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Mountain View, California", // Visit KA
    "Toronto, Canada",
    "Waterloo, Canada", // Badminton Tournament
    "Toronto, Canada",
    "Montreal, Canada", // Cruise cancelled
    "Toronto, Canada",
    "New York, New York", // Trip with SE friends
    "Toronto, Canada",
    // September -> December 2012 (3B) - 350 Lester
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Montreal, Canada",
    // January -> April 2013 (Square)
    "Ottawa, Canada",
    "San Francisco, California",
    "Los Angeles, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Mountain View, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Yosemite National Park, California",
    "San Francisco, California",
    "Waikiki, Hawaii",
    "San Francisco, California",
    // May -> August 2013 (4A) - 350 Lester
    "Ottawa, Canada",
    "Waterloo, Canada",
    "Tobermory, Canada", // Camping
    "Waterloo, Canada",
    "Niagara Falls, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // September -> December 2013 (Eurotrip)
    "Ottawa, Canada",
    "Toronto, Canada",
    "Rome, Italy",
    "Florence, Italy",
    "La Spezia, Italy",
    "Venice, Italy",
    "Copenhagen, Denmark",
    "Amsterdam, Holland",
    "London, England",
    "Lyon, France",
    "Paris, France",
    "Toulouse, France",
    "Barcelona, Spain",
    "Granada, Spain",
    "Madrid, Spain",
    "Dublin, Ireland",
    "Edinburgh, Scotland",
    "London, England",
    "Oxford, England",
    "London, England",
    "Doncaster, England",
    "London, England",
    "Oslo, Norway",
    "Brussels, Belgium",
    "Berlin, Germany",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "San Jose, California",
    "San Francisco, California",
    "San Jose, California",
    "San Francisco, California",
    "Ottawa, Canada",
  ],
  "ca": [
    "NORTH VANCOUVER, BC, CANADA",
    "Burnaby, British Columbia, Canada",
    "SARNIA, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "NEWMARKET, ON, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "SIMCOE, ON, CANADA",
    "Calgary (and vicinity), Alberta, Canada",
    "ETOBICOKE, ON, CANADA",
    "Tokyo (and vicinity), Japan",
    "TORONTO, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "NORTH YORK, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "PETERBOROUGH, ON, CANADA",
    "St. Martin (French), St. Martin",
    "WELLAND, ON, CANADA",
    "Metro Toronto Convention Centre, Toronto, Ontario, Canada",
    "CALGARY, AB, CANADA",
    "Banff National Park, Alberta, Canada",
    "WINDSOR, ON, CANADA",
    "Nara (and vicinity), Japan",
    "TORONTO, ON, CANADA",
    "San Francisco (and vicinity), California, United States of America",
    "NORTH YORK, ON, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "NORTH VANCOUVER, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "KITCHENER, ON, CANADA",
    "Niagara Falls (and vicinity), New York, United States of America",
    "SARNIA, ON, CANADA",
    "Chattanooga (and vicinity), Tennessee, United States of America",
    "GRANDE PRAIRIE, AB, CANADA",
    "Guadalajara (and vicinity), Jalisco, Mexico",
    "MOOSE JAW, SK, CANADA",
    "Moose Jaw, Saskatchewan, Canada",
    "VANCOUVER, BC, CANADA",
    "Auckland (and vicinity), New Zealand",
    "LANGRUTH, MB, CANADA",
    "Winnipeg (and vicinity), Manitoba, Canada",
    "NORTH YORK, ON, CANADA",
    "Niagara Falls (and vicinity), New York, United States of America",
    "OAKVILLE, ON, CANADA",
    "Jeddah, Saudi Arabia",
    "WINNIPEG, MB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "OTTAWA, ON, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "DELTA, BC, CANADA",
    "New York (and vicinity), New York, United States of America",
    "MOOSE JAW, SK, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "VANCOUVER, BC, CANADA",
    "San Francisco (and vicinity), California, United States of America",
    "SURREY, BC, CANADA",
    "Downtown Los Angeles, California, United States of America",
    "LAVAL, QC, CANADA",
    "Fort Lauderdale (and vicinity), Florida, United States of America",
    "ETOBICOKE, ON, CANADA",
    "Ottawa (and vicinity), Ontario, Canada",
    "VANCOUVER, BC, CANADA",
    "Newport, Oregon, United States of America",
    "EDMONTON, AB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "CALGARY, AB, CANADA",
    "Banff, Alberta, Canada",
    "TORONTO, ON, CANADA",
    "New York (and vicinity), New York, United States of America",
    "CALGARY, AB, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "THUNDER BAY, ON, CANADA",
    "Barrie - Orillia (and vicinity), Ontario, Canada",
    "VERDUN, QC, CANADA",
    "Phnom Penh City Centre, Cambodia",
    "ETOBICOKE, ON, CANADA",
    "Tokyo (and vicinity), Japan",
    "TORONTO, ON, CANADA",
    "Hotel Zone, Cancun, Quintana Roo, Mexico",
    "REGINA, SK, CANADA",
    "Prince Albert, Saskatchewan, Canada",
    "KELOWNA, BC, CANADA",
    "Portland (and vicinity), Oregon, United States of America",
    "TORONTO, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "MONTREAL, QC, CANADA",
    "Broadway - Times Square, New York, New York, United States of America",
    "CAMBRIDGE, ON, CANADA",
    "Quebec (and vicinity), Quebec, Canada",
    "BEAUHARNOIS, QC, CANADA",
    "Stockholm (and vicinity), Sweden",
    "SURREY, BC, CANADA",
    "Trudeau International Airport (YUL), Quebec, Canada",
    "OAKVILLE, ON, CANADA",
    "Samana (and vicinity), Dominican Republic",
    "TORONTO, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "KINGSTON, ON, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "VANCOUVER, BC, CANADA",
    "Surrey, British Columbia, Canada",
    "TEMPLE, TX, UNITED STATES OF AMERICA",
    "Baton Rouge (and vicinity), Louisiana, United States of America",
    "MILTON, ON, CANADA",
    "Trudeau International Airport (YUL), Quebec, Canada",
    "ETOBICOKE, ON, CANADA",
    "Mississauga, Ontario, Canada",
    "THORNHILL, ON, CANADA",
    "Buffalo (and vicinity), New York, United States of America",
    "CORDOBA, CO, SPAIN & CANARY ISLANDS",
    "Madrid (and vicinity), Spain",
    "WHITEHORSE, YT, CANADA",
    "Parksville, British Columbia, Canada",
    "MILTON, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "OROMOCTO, NB, CANADA",
    "Fort Myers (and vicinity), Florida, United States of America",
    "LONDON, ON, CANADA",
    "Niagara Falls, Ontario, Canada",
    "SARNIA, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "VICTORIA, BC, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "NEWMARKET, ON, CANADA",
    "Quebec (and vicinity), Quebec, Canada",
    "TORONTO, ON, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "BOWMANVILLE, ON, CANADA",
    "Niagara Falls (and vicinity), New York, United States of America",
    "TORONTO, ON, CANADA",
    "Niagara Falls, Ontario, Canada",
    "LONGUEUIL, QC, CANADA",
    "San Jose (and vicinity), Costa Rica",
    "CALGARY, AB, CANADA",
    "Banff National Park, Alberta, Canada",
    "TORONTO, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "MARKHAM, ON, CANADA",
    "Niagara Falls, Ontario, Canada",
    "MONTREAL, QC, CANADA",
    "Cancun (and vicinity), Quintana Roo, Mexico",
    "CALGARY, AB, CANADA",
    "Lake Forest, California, United States of America",
    "DAWSON CREEK, BC, CANADA",
    "Banff National Park, Alberta, Canada",
    "LONGUEUIL, QC, CANADA",
    "Munich (and vicinity), Germany",
    "RICHMOND, BC, CANADA",
    "Heathrow Airport (LHR), England, United Kingdom",
    "BEDFORD, NS, CANADA",
    "Bangor (and vicinity), Maine, United States of America",
    "VIENTIANE, VT, LAOS",
    "Vang Vieng, Laos",
    "CALGARY, AB, CANADA",
    "Hollywood, California, United States of America",
    "NORTH YORK, ON, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "CALGARY, AB, CANADA",
    "Richmond, British Columbia, Canada",
    "SAINTE-MARIE, QC, CANADA",
    "Cartagena (and vicinity), Colombia",
    "NANAIMO, BC, CANADA",
    "Tofino (and vicinity), British Columbia, Canada",
    "VANCOUVER, BC, CANADA",
    "Charlotte-Douglas International Airport (CLT), North Carolina, United States of America",
    "BURLINGTON, ON, CANADA",
    "Banff Centre, Banff, Alberta, Canada",
    "SASKATOON, SK, CANADA",
    "Kelowna, British Columbia, Canada",
    "WETASKIWIN, AB, CANADA",
    "Banff, Alberta, Canada",
    "SUDBURY, ON, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "MONTREAL, QC, CANADA",
    "Sutton, Quebec, Canada",
    "BANFF, AB, CANADA",
    "Jasper National Park (area), Alberta, Canada",
    "BEACONSFIELD, QC, CANADA",
    "Parsippany (and vicinity), New Jersey, United States of America",
    "MONTREAL, QC, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "THORNHILL, ON, CANADA",
    "Fort Lauderdale (and vicinity), Florida, United States of America",
    "RICHMOND HILL, ON, CANADA",
    "Chicago (and vicinity), Illinois, United States of America",
    "MEDICINE HAT, AB, CANADA",
    "Calgary International Airport (YYC), Alberta, Canada",
    "TORONTO, ON, CANADA",
    "Blue Mountains, Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Grand Canyon (and vicinity), Arizona, United States of America",
    "ETOBICOKE, ON, CANADA",
    "Miami, FL, United States (MIA-Miami Intl.)",
    "LETHBRIDGE, AB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "SALT SPRING ISLAND, BC, CANADA",
    "Palm Springs, CA, United States (PSP-Palm Springs Intl.)",
    "WOODBRIDGE, ON, CANADA",
    "Old Town, Zurich, Switzerland",
    "VANCOUVER, BC, CANADA",
    "North Vancouver, British Columbia, Canada",
    "VANCOUVER, BC, CANADA",
    "Frankfurt Airport (FRA), Germany",
    "COQUITLAM, BC, CANADA",
    "Union Square, San Francisco, California, United States of America",
    "COQUITLAM, BC, CANADA",
    "Long Beach, California, United States of America",
    "TORONTO, ON, CANADA",
    "Portland (and vicinity), Oregon, United States of America",
    "NORTH VANCOUVER, BC, CANADA",
    "Honolulu, Hawaii, United States of America",
    "CALGARY, AB, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "TORONTO, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "NORTH VANCOUVER, BC, CANADA",
    "Portland (and vicinity), Oregon, United States of America",
    "CALGARY, AB, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "SASKATOON, SK, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "EDMONTON, AB, CANADA",
    "Victoria (and vicinity), British Columbia, Canada",
    "ELMVALE, ON, CANADA",
    "Leduc - Edmonton International Airport (YEG), Alberta, Canada",
    "WATERLOO, ON, CANADA",
    "Los Angeles (and vicinity), California, United States of America",
    "MONTREAL, QC, CANADA",
    "Kelowna, British Columbia, Canada",
    "NORTH YORK, ON, CANADA",
    "San Diego (county), California, United States of America",
    "MAGOG, QC, CANADA",
    "Trois-Rivieres, Quebec, Canada",
    "EDMONTON, AB, CANADA",
    "Downtown Calgary, Alberta, Canada",
    "VANCOUVER, BC, CANADA",
    "Atlanta (and vicinity), Georgia, United States of America",
    "PETERBOROUGH, ON, CANADA",
    "Toronto West - Pearson International Airport (YYZ), Ontario, Canada",
    "WINNIPEG, MB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "KITCHENER, ON, CANADA",
    "New York (and vicinity), New York, United States of America",
    "MINDEN, ON, CANADA",
    "St. Marys, Ontario, Canada",
    "MOUNT PEARL, NL, CANADA",
    "Washington (and vicinity), District of Columbia, United States of America",
    "SURREY, BC, CANADA",
    "Bergen - Hordaland (county), Norway",
    "MISSISSAUGA, ON, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "SASKATOON, SK, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "ORLEANS, ON, CANADA",
    "Rocky Mount (and vicinity), North Carolina, United States of America",
    "VANCOUVER, BC, CANADA",
    "Cusco, Peru",
    "KITCHENER, ON, CANADA",
    "South Beach, Miami Beach, Florida, United States of America",
    "VANCOUVER, BC, CANADA",
    "Orange County, California, United States of America",
    "VANCOUVER, BC, CANADA",
    "Aldergrove, British Columbia, Canada",
    "BARRHEAD, AB, CANADA",
    "Valemount (and vicinity), British Columbia, Canada",
    "BARRHEAD, AB, CANADA",
    "Hinton, Alberta, Canada",
    "SHERBROOKE, QC, CANADA",
    "Ixtapa - Zihuatanejo (and vicinity), Guerrero, Mexico",
    "SCARBOROUGH, ON, CANADA",
    "Bloomsbury, London, England, United Kingdom",
    "MIDWAY, BC, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "AIRDRIE, AB, CANADA",
    "Kamloops (and vicinity), British Columbia, Canada",
    "OTTAWA, ON, CANADA",
    "Downtown Montreal, Quebec, Canada",
    "CALGARY, AB, CANADA",
    "Sunset Strip, West Hollywood, California, United States of America",
    "VANCOUVER, BC, CANADA",
    "Richmond, British Columbia, Canada",
    "CALGARY, AB, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "REGINA, SK, CANADA",
    "Penticton, British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "BRAMPTON, ON, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "ORILLIA, ON, CANADA",
    "Vancouver International Airport (YVR), British Columbia, Canada",
    "WATERLOO, ON, CANADA",
    "San Diego (county), California, United States of America",
    "TORONTO, ON, CANADA",
    "Kingston (and vicinity), Ontario, Canada",
    "DURBAN, ZN, SOUTH AFRICA",
    "Blyde River Canyon, Ohrigstad, South Africa",
    "SCARBOROUGH, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "BAKU, BA, AZERBAIJAN",
    "Istanbul (and vicinity), Turkey",
    "NORTH YORK, ON, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "VANCOUVER, BC, CANADA",
    "Geneva (and vicinity), Switzerland",
    "PALM DESERT, CA, UNITED STATES OF AMERICA",
    "Palm Springs (and vicinity), California, United States of America",
    "COQUITLAM, BC, CANADA",
    "Whistler, British Columbia, Canada",
    "BRANTFORD, ON, CANADA",
    "Riviera Maya, Quintana Roo, Mexico",
    "FREELAND, MI, UNITED STATES OF AMERICA",
    "San Diego (county), California, United States of America",
    "CAMBRIDGE, ON, CANADA",
    "Cambridge, Ontario, Canada",
    "COQUITLAM, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "BELLEVILLE, ON, CANADA",
    "Scarborough, Toronto, Ontario, Canada",
    "CALGARY, AB, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "CHRISTCHURCH, CAN, NEW ZEALAND",
    "Honolulu, Hawaii, United States of America",
    "BURNABY, BC, CANADA",
    "San Francisco (and vicinity), California, United States of America",
    "TOLUCA, MEX, MEXICO",
    "Puerto Vallarta, Jalisco, Mexico (PVR-Licenciado Gustavo Diaz Ordaz Intl.)",
    "RICHMOND HILL, ON, CANADA",
    "Miami International Airport (MIA), Florida, United States of America",
    "DALLAS, TX, UNITED STATES OF AMERICA",
    "Orlando International Airport (MCO), Florida, United States of America",
    "EDMONTON, AB, CANADA",
    "Isla Mujeres, Quintana Roo, Mexico",
    "VANCOUVER, BC, CANADA",
    "Malaga, Spain",
    "VANCOUVER, BC, CANADA",
    "Portland (and vicinity), Oregon, United States of America",
    "VANCOUVER, BC, CANADA",
    "Downtown Victoria, Victoria, British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Squamish, British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Napa Valley, California, United States of America",
    "TORONTO, ON, CANADA",
    "London (and vicinity), England, United Kingdom",
    "SCARBOROUGH, ON, CANADA",
    "Myrtle Beach (and vicinity), South Carolina, United States of America",
    "VANCOUVER, BC, CANADA",
    "Downtown Seattle, Washington, United States of America",
    "STITTSVILLE, ON, CANADA",
    "Hamilton, Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Sudbury (and vicinity), Ontario, Canada",
    "KINGSTON, ON, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "MONTREAL, QC, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "SHERWOOD PARK, AB, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "MIDWAY, BC, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "REGINA, SK, CANADA",
    "West Edmonton (area), Alberta, Canada",
    "SCARBOROUGH, ON, CANADA",
    "Niagara Falls, Ontario, Canada",
    "MONTREAL, QC, CANADA",
    "London (and vicinity), England, United Kingdom",
    "CANCUN, ROO, MEXICO",
    "Hotel Zone, Cancun, Quintana Roo, Mexico",
    "CALGARY, AB, CANADA",
    "San Diego (county), California, United States of America",
    "EDMONTON, AB, CANADA",
    "Scottsdale, Arizona, United States of America",
    "TORONTO, ON, CANADA",
    "Pittsburgh (and vicinity), Pennsylvania, United States of America",
    "NORTH YORK, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Fort Lauderdale (and vicinity), Florida, United States of America",
    "TORONTO, ON, CANADA",
    "The Strip (Las Vegas), Nevada, United States of America",
    "MAPLE, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "VANCOUVER, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "CALGARY, AB, CANADA",
    "Salt Lake City (and vicinity), Utah, United States of America",
    "MONTREAL, QC, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "AMHERST, NS, CANADA",
    "Downtown Montreal, Quebec, Canada",
    "WINNIPEG, MB, CANADA",
    "Merida (and vicinity), Yucatan, Mexico",
    "GATINEAU, QC, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "BINBROOK, ON, CANADA",
    "Union Square, San Francisco, California, United States of America",
    "OKEECHOBEE, FL, UNITED STATES OF AMERICA",
    "Orlando (and vicinity), Florida, United States of America",
    "KINGSTON, ON, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "HALIFAX, NS, CANADA",
    "Eaton Centre, Montreal, Quebec, Canada",
    "ST. JOHN'S, NL, CANADA",
    "Port Canaveral, Cape Canaveral, Florida, United States of America",
    "VANCOUVER, BC, CANADA",
    "Newport Beach, California, United States of America",
    "WELLAND, ON, CANADA",
    "Downtown Toronto, Ontario, Canada",
    "VICTORIA, BC, CANADA",
    "Santa Marta (and vicinity), Colombia",
    "VICTORIA, BC, CANADA",
    "Downtown Vancouver, British Columbia, Canada",
    "VANCOUVER, BC, CANADA",
    "Vancouver International Airport (YVR), British Columbia, Canada",
    "MASCOUCHE, QC, CANADA",
    "Jay Peak Ski Resort, Jay, Vermont, United States of America",
    "BARRIE, ON, CANADA",
    "Calgary International Airport (YYC), Alberta, Canada",
    "VANCOUVER, BC, CANADA",
    "Los Angeles (and vicinity), California, United States of America",
    "NORTH YORK, ON, CANADA",
    "Patong, Thailand",
    "NORTH YORK, ON, CANADA",
    "Universal Studios Florida, Orlando, Florida, United States of America",
    "SYDNEY, NS, CANADA",
    "Downtown Montreal, Quebec, Canada",
    "VICTORIA, BC, CANADA",
    "Langford, Victoria, British Columbia, Canada",
    "SURREY, BC, CANADA",
    "Disneyland - Anaheim, California, United States of America",
    "NORTH YORK, ON, CANADA",
    "Quebec (and vicinity), Quebec, Canada",
    "WESTMOUNT, QC, CANADA",
    "Chelsea, New York, New York, United States of America",
    "TORONTO, ON, CANADA",
    "Halifax (and vicinity), Nova Scotia, Canada",
    "NORTH YORK, ON, CANADA",
    "Downtown Montreal, Quebec, Canada",
    "EDMONTON, AB, CANADA",
    "Downtown Calgary, Alberta, Canada",
    "MONTREAL, QC, CANADA",
    "Cozumel, Quintana Roo, Mexico",
    "KINGSTON, ON, CANADA",
    "Mecca, Saudi Arabia",
    "SURREY, BC, CANADA",
    "Victoria (and vicinity), British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "BURNABY, BC, CANADA",
    "Downtown Montreal, Quebec, Canada",
    "MONTREAL, QC, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "WOODBRIDGE, ON, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "SCHAERBEEK, BRU, BELGIUM",
    "North Conway, New Hampshire, United States of America",
    "MONTREAL, QC, CANADA",
    "Trois-Rivieres (and vicinity), Quebec, Canada",
    "CALGARY, AB, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "CALGARY, AB, CANADA",
    "Calgary International Airport (YYC), Alberta, Canada",
    "COQUITLAM, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "MARKHAM, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "GUELPH, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "VANCOUVER, BC, CANADA",
    "Seattle (and vicinity), Washington, United States of America",
    "MARKHAM, ON, CANADA",
    "St. Jerome, Quebec, Canada",
    "ETOBICOKE, ON, CANADA",
    "Bridgetown, Barbados (BGI-Grantley Adams Intl.)",
    "SCARBOROUGH, ON, CANADA",
    "Stratford (and vicinity), Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Eilat (and vicinity), Israel",
    "CHATEAUGUAY, QC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "VANCOUVER, BC, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "CALGARY, AB, CANADA",
    "Victoria (and vicinity), British Columbia, Canada",
    "ETOBICOKE, ON, CANADA",
    "Queenstown, New Zealand",
    "EDMONTON, AB, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "EDMONTON, AB, CANADA",
    "Downtown Edmonton, Alberta, Canada",
    "MONTREAL, QC, CANADA",
    "Managua (and vicinity), Nicaragua",
    "CAMPBELL RIVER, BC, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "VANCOUVER, BC, CANADA",
    "Downtown Vancouver, British Columbia, Canada",
    "VANCOUVER, BC, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "KANATA, ON, CANADA",
    "Rome (and vicinity), Italy",
    "TORONTO, ON, CANADA",
    "Punta Cana (and vicinity), Dominican Republic",
    "MONTREAL, QC, CANADA",
    "Chicago (and vicinity), Illinois, United States of America",
    "CALGARY, AB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "CALGARY, AB, CANADA",
    "Honolulu, Hawaii, United States of America",
    "EDMONTON, AB, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "MONTREAL, QC, CANADA",
    "Trudeau International Airport (YUL), Quebec, Canada",
    "CALGARY, AB, CANADA",
    "Burnaby, British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Niagara Falls, Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Phoenix (and vicinity), Arizona, United States of America",
    "MONCTON, NB, CANADA",
    "Belleair Beach, Florida, United States of America",
    "FREDERICTON, NB, CANADA",
    "Downtown Miami, Florida, United States of America",
    "TORONTO, ON, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "CALGARY, AB, CANADA",
    "Canmore, Alberta, Canada",
    "BARRIE, ON, CANADA",
    "Kingston (and vicinity), Ontario, Canada",
    "BRAMPTON, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "CALGARY, AB, CANADA",
    "Edmonton (and vicinity), Alberta, Canada",
    "BURNABY, BC, CANADA",
    "Union Square, San Francisco, California, United States of America",
    "MISSISSAUGA, ON, CANADA",
    "Tokyo (and vicinity), Japan",
    "CALGARY, AB, CANADA",
    "Miami International Airport (MIA), Florida, United States of America",
    "COMERCIO, BA, BRAZIL",
    "Rio de Janeiro (and vicinity), Brazil",
    "TORONTO, ON, CANADA",
    "Fort Lauderdale (and vicinity), Florida, United States of America",
    "VANCOUVER, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "WABIGOON, ON, CANADA",
    "Thunder Bay, Ontario, Canada",
    "THORNHILL, ON, CANADA",
    "Queens, New York, United States of America",
    "EDMONTON, AB, CANADA",
    "Overland Park, Kansas, United States of America",
    "MARKHAM, ON, CANADA",
    "Pahrump, Nevada, United States of America",
    "SCARBOROUGH, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Union Square, San Francisco, California, United States of America",
    "SCARBOROUGH, ON, CANADA",
    "Banff National Park, Alberta, Canada",
    "TORONTO, ON, CANADA",
    "Myrtle Beach (and vicinity), South Carolina, United States of America",
    "CAMROSE, AB, CANADA",
    "Banff, Alberta, Canada",
    "QUEBEC, QC, CANADA",
    "Dubai Emirate, United Arab Emirates",
    "MARKHAM, ON, CANADA",
    "Pretoria, South Africa",
    "BEAUHARNOIS, QC, CANADA",
    "Stockholm (and vicinity), Sweden",
    "MARKHAM, ON, CANADA",
    "Quebec (and vicinity), Quebec, Canada",
    "COQUITLAM, BC, CANADA",
    "Las Vegas (and vicinity), Nevada, United States of America",
    "UXBRIDGE, ON, CANADA",
    "Atlanta (and vicinity), Georgia, United States of America",
    "QUEBEC, QC, CANADA",
    "San Jose, Costa Rica (SJO-Juan Santamaria Intl.)",
    "NORTH YORK, ON, CANADA",
    "Chicago (and vicinity), Illinois, United States of America",
    "TORONTO, ON, CANADA",
    "Hanoi (and vicinity), Vietnam",
    "CALGARY, AB, CANADA",
    "Banff National Park, Alberta, Canada",
    "RICHMOND, BC, CANADA",
    "Seattle (and vicinity), Washington, United States of America",
    "WESTLAND, MI, UNITED STATES OF AMERICA",
    "Seoul (and vicinity), South Korea",
    "WATERLOO, ON, CANADA",
    "San Juan, Puerto Rico",
    "MANAGUA, MN, NICARAGUA",
    "Managua (and vicinity), Nicaragua",
    "OTTAWA, ON, CANADA",
    "Varanasi, India",
    "NORTH YORK, ON, CANADA",
    "Zermatt, Switzerland",
    "HAMILTON, ON, CANADA",
    "Sri Lanka (all)",
    "POINTE-CLAIRE, QC, CANADA",
    "Luxor, Egypt",
    "WESTBANK, BC, CANADA",
    "Richmond, British Columbia, Canada",
    "TORONTO, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "BURNABY, BC, CANADA",
    "Gangnam, Seoul, South Korea",
    "RED DEER, AB, CANADA",
    "Pincher Creek, Alberta, Canada",
    "SIDNEY, BC, CANADA",
    "North Vancouver, British Columbia, Canada",
    "MARKHAM, ON, CANADA",
    "Blue Mountains, Ontario, Canada",
    "MARKHAM, ON, CANADA",
    "Montreal (and vicinity), Quebec, Canada",
    "OTTAWA, ON, CANADA",
    "Sweimeh, Jordan",
    "KINGSTON, ON, CANADA",
    "Toronto (and vicinity), Ontario, Canada",
    "WATERLOO, ON, CANADA",
    "Vancouver (and vicinity), British Columbia, Canada",
    "ETOBICOKE, ON, CANADA",
    "Bridgetown, Barbados (BGI-Grantley Adams Intl.)",
    "NORTH YORK, ON, CANADA",
    "Niagara Falls (and vicinity), Ontario, Canada",
    "TORONTO, ON, CANADA",
    "Cali (and vicinity), Colombia",
    "SURREY, BC, CANADA",
    "Atlanta (and vicinity), Georgia, United States of America",
    "TORONTO, ON, CANADA",
    "Orlando (and vicinity), Florida, United States of America",
    "NORTH BAY, ON, CANADA",
    "London (and vicinity), Ontario, Canada",
    "PICKERING, ON, CANADA",
    "Downtown Ottawa, Ontario, Canada"
  ],
  "de": [
    "ALBSTADT, BW, GERMANY",
    "Paris (and vicinity), France",
    "MUNICH, BY, GERMANY",
    "Berlin (and vicinity), Germany",
    "BERLIN, BE, GERMANY",
    "Fuerth, Germany",
    "SINGAPORE, 01, SINGAPORE",
    "Singapore (all), Singapore",
    "LE PORT, nan, REUNION",
    "Moenchengladbach, Germany",
    "FRANKFURT AM MAIN, HE, GERMANY",
    "Hobart (and vicinity), Tasmania, Australia",
    "COESFELD, NW, GERMANY",
    "Little Rock (and vicinity), Arkansas, United States of America",
    "WITTEN, NW, GERMANY",
    "Berlin (and vicinity), Germany",
    "INGOLSTADT, BY, GERMANY",
    "New York (and vicinity), New York, United States of America",
    "BERGISCH GLADBACH, NW, GERMANY",
    "Berlin (and vicinity), Germany",
    "LOHMAR, NW, GERMANY",
    "SoHo - Tribeca, New York, United States of America",
    "COLOGNE, NW, GERMANY",
    "Bologna (province), Italy",
    "REGENSBURG, BY, GERMANY",
    "Rome (and vicinity), Italy",
    "MOSCOW, MOW, RUSSIA",
    "Prague City Center, Prague, Czech Republic",
    "HANNOVER, NI, GERMANY",
    "Prague (and vicinity), Czech Republic",
    "FURSTENFELDBRUCK, BY, GERMANY",
    "Sri Lanka (all)",
    "MUNICH, BY, GERMANY",
    "Silom, Bangkok, Thailand",
    "FRANKFURT AM MAIN, HE, GERMANY",
    "Medan, Indonesia",
    "MASSENBACHHAUSEN, BW, GERMANY",
    "GERMIGNAGA, VA, ITALY",
    "Sarasota (and vicinity), Florida, United States of America",
    "GRAZ, 6, AUSTRIA",
    "Amsterdam (and vicinity), Netherlands",
    "SIEGEN, NW, GERMANY",
    "Prague (and vicinity), Czech Republic",
    "FRANKFURT AM MAIN, HE, GERMANY",
    "Hobart (and vicinity), Tasmania, Australia",
    "ALTENA, NW, GERMANY",
    "Istanbul (and vicinity), Turkey",
    "DORTMUND, NW, GERMANY",
    "Budapest (and vicinity), Hungary",
    "RECKLINGHAUSEN, NW, GERMANY",
    "Windhoek, Namibia",
    "COLOGNE, NW, GERMANY",
    "Marlborough, New Zealand",
    "HAMBURG, HH, GERMANY",
    "Fort Myers (and vicinity), Florida, United States of America",
    "HAAR, BY, GERMANY",
    "Sydney (and vicinity), New South Wales, Australia",
    "WIESBADEN, HE, GERMANY",
    "Izmir (area), Turkey",
    "MUNICH, BY, GERMANY",
    "Mauritius Island, Mauritius",
    "HAMBURG, HH, GERMANY",
    "Amsterdam (and vicinity), Netherlands",
    "TEHRAN, 07, IRAN",
    "Paris (and vicinity), France",
    "ZURICH, ZH, SWITZERLAND",
    "Prague (and vicinity), Czech Republic",
    "NUREMBERG, BY, GERMANY",
    "Prague (and vicinity), Czech Republic",
    "FRANKFURT AM MAIN, HE, GERMANY",
    "New York (and vicinity), New York, United States of America",
    "RUSSELSHEIM, HE, GERMANY",
    "Oslo (and vicinity), Norway",
    "NUREMBERG, BY, GERMANY",
    "Barcelona (and vicinity), Spain",
    "DUSSELDORF, NW, GERMANY",
    "Tulum, Quintana Roo, Mexico",
    "LEIPZIG, SN, GERMANY",
    "Side, Turkey",
    "BERLIN, BE, GERMANY",
    "Louvre - Place Vendome (1 arr. and 2 arr.), Paris, France",
    "EBIKON, LU, SWITZERLAND",
    "New York (and vicinity), New York, United States of America",
    "LAS VEGAS, NV, UNITED STATES OF AMERICA",
    "Kanab, Utah, United States of America",
    "HAMBURG, HH, GERMANY",
    "Venice (and vicinity), Italy",
    "MUNICH, BY, GERMANY",
    "Liverpool (and vicinity), England, United Kingdom",
    "BERLIN, BE, GERMANY",
    "Amsterdam (and vicinity), Netherlands",
    "MUNICH, BY, GERMANY",
    "New York (and vicinity), New York, United States of America",
    "BERLIN, BE, GERMANY",
    "South Beach, Miami Beach, Florida, United States of America",
    "AUGSBURG, BY, GERMANY",
    "New York (and vicinity), New York, United States of America",
    "MUNICH, BY, GERMANY",
    "Hannover (and vicinity), Germany",
    "DIEBURG, HE, GERMANY",
    "Porto (and vicinity), Portugal",
    "MONTEVIDEO, MO, URUGUAY",
    "Buenos Aires, Argentina (EZE-Ministro Pistarini Intl.)",
    "MUNICH, BY, GERMANY",
    "Abu Dhabi Emirate, United Arab Emirates",
    "BERGISCH GLADBACH, NW, GERMANY",
    "Odessa, Ukraine",
    "FRIEDRICHSDORF, HE, GERMANY",
    "Madrid (and vicinity), Spain",
    "WIMSHEIM, BW, GERMANY",
    "Nelson, New Zealand",
    "WERBACH, BW, GERMANY",
    "Dubai Emirate, United Arab Emirates",
    "DORTMUND, NW, GERMANY",
    "Saint Pauli, Hamburg, Germany",
    "MUNICH, BY, GERMANY",
    "Vienna (and vicinity), Austria",
    "MUNICH, BY, GERMANY",
    "Bangkok (and vicinity), Thailand",
    "FRANKFURT AM MAIN, HE, GERMANY",
    "Hobart (and vicinity), Tasmania, Australia",
    "NUREMBERG, BY, GERMANY",
    "Arnhem (and vicinity), Netherlands"
  ]
};
