module.exports = {
  "com": [
    "Ottawa, Canada",
    // 2005
    "Ottawa, Ontario",
    "Stratford, Ontario",
    // 2007
    "Ottawa, Ontario",
    "Toronto, Canada",
    // 2009
    "Ottawa, Ontario",
    "Toronto, Canada",
    "Ottawa, Ontario",
    "Kingston, Ontario",
    "Ottawa, Ontario",
    "Waterloo, Ontario",
    "Ottawa, Ontario",
    // September -> December 2009 (1A) - Village 1
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada", // Thanksgiving
    "Waterloo, Canada",
    "Hamilton, Canada", // ACM Regionals
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2010 (1B) - Velocity
    "Waterloo, Canada",
    // March -> August 2010 (TWG)
    "Toronto, Canada",
    // September -> December 2010 (2A) - Glenelm
    "Waterloo, Canada",
    "London, Canada", // Yuxuan's 19th
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Niagara Falls, Canada", // 2 yr anniv
    "Waterloo, Canada",
    "Ottawa, Canada",
    // January -> April 2011 (Kontagent)
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    // May -> August 2011 (2B) - Glenelm
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Ottawa, Canada", // mom's birthday
    "Waterloo, Canada",
    "Ottawa, Canada", // mom's retirement
    "Waterloo, Canada",
    "Ottawa, Canada", // G test
    "Waterloo, Canada",
    // September -> December 2011 (Facebook)
    "Ottawa, Canada",
    "Toronto, Canada",
    "San Francisco, California",
    "Toronto, Canada",
    "Ottawa, Canada",
    // January -> April 2012 (3A) - Velocity
    "Toronto, Canada",
    "Waterloo, Canada",
    "Montreal, Canada", // CUSEC
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // May -> August 2013 (Khan Academy, Remote from Toronto)
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Mountain View, California", // Visit KA
    "Toronto, Canada",
    "Waterloo, Canada", // Badminton Tournament
    "Toronto, Canada",
    "Montreal, Canada", // Cruise cancelled
    "Toronto, Canada",
    "New York, New York", // Trip with SE friends
    "Toronto, Canada",
    // September -> December 2012 (3B) - 350 Lester
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Ottawa, Canada",
    "Montreal, Canada",
    // January -> April 2013 (Square)
    "Ottawa, Canada",
    "San Francisco, California",
    "Los Angeles, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Mountain View, California",
    "San Francisco, California",
    "South Lake Tahoe, California",
    "San Francisco, California",
    "Yosemite National Park, California",
    "San Francisco, California",
    "Waikiki, Hawaii",
    "San Francisco, California",
    // May -> August 2013 (4A) - 350 Lester
    "Ottawa, Canada",
    "Waterloo, Canada",
    "Tobermory, Canada", // Camping
    "Waterloo, Canada",
    "Niagara Falls, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "Waterloo, Canada",
    // September -> December 2013 (Eurotrip)
    "Ottawa, Canada",
    "Toronto, Canada",
    "Rome, Italy",
    "Florence, Italy",
    "La Spezia, Italy",
    "Venice, Italy",
    "Copenhagen, Denmark",
    "Amsterdam, Holland",
    "London, England",
    "Lyon, France",
    "Paris, France",
    "Toulouse, France",
    "Barcelona, Spain",
    "Granada, Spain",
    "Madrid, Spain",
    "Dublin, Ireland",
    "Edinburgh, Scotland",
    "London, England",
    "Oxford, England",
    "London, England",
    "Doncaster, England",
    "London, England",
    "Oslo, Norway",
    "Brussels, Belgium",
    "Berlin, Germany",
    "Toronto, Canada",
    "Waterloo, Canada",
    "Toronto, Canada",
    "San Jose, California",
    "San Francisco, California",
    "San Jose, California",
    "San Francisco, California",
    "Ottawa, Canada",
  ],
  "ca": [
    "Ottawa, Canada",
    "Peterborough, Canada",
    "Ottawa, Canada",
    "Peterborough, Canada",
    "Ottawa, Canada",
    "Ashover, England",
    "Ottawa, Canada",
    // 2007 - 2008
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // 2009
    "Toronto, Canada",
    "New York, New York",
    "Toronto, Canada",
    "Ottawa, Canada",
    // 2010
    "Toronto, Canada",
    "Winnipeg, Manitoba",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Winnipeg, Manitoba",
    "Ottawa, Canada",
    // 2011
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    "Vancouver, Canada",
    "Ottawa, Canada",
    // 2012
    "Toronto, Canada",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Blue Mountain, Canada",
    "Toronto, Canada",
    "Ottawa, Canada",
    // 2013
    "Palm Bay, Florida",
    "Ottawa, Canada",
    "Palm Bay, Florida",
    "Ottawa, Canada",
    "Toronto, Canada",
    "Innisfil, Canada", // Belle Ewart
    "Ottawa, Canada",
  ],
  "de": [
    "Ottawa, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Canada",
    "Kingston, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Burlington, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Kingston, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // 1998
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // 1999
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // 2000
    "Milan, Italy",
    "Venice, Italy",
    "Florence, Italy",
    "Assisi, Italy",
    "Sorrento, Italy",
    "Rome, Italy",
    "Huntsville, Ontario, Canada",
    "Rivière Kipawa, Quebec, Canada",
    "Huntsville, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada", // (NHS Graduation)
    "Calgary, Alberta, Canada",
    "Bishop, California, USA",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    // 2003
    "Edmonton, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    "Penticton, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    // 2004
    "Calgary, Alberta, Canada",
    "Edmonton, Alberta, Canada",
    "McBride, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada",
    // 2005
    "San Jose, Costa Rica",
    "Santa Teresa, Costa Rica",
    "San Jose, Costa Rica",
    "Calgary, Alberta, Canada",
    "Canmore, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Alicante, Spain",
    "Valencia, Spain",
    "Oropesa del Mar, Spain",
    "Barcelona, Spain",
    "Vaqueira, Spain",
    "Zarautz, Spain",
    "San Sebastian, Spain",
    "Barcelona, Spain",
    "Doncaster, England",
    "Paris, France",
    "Interlaken, Switzerland",
    "Grindelwald, Switzerland",
    "Interlaken, Switzerland",
    "Grindelwald, Switzerland",
    "Interlaken, Switzerland",
    "Ottawa, Ontario, Canada",
    "London, Ontario, Canada",
    "Crested Butte, Colorado, USA",
    "Breckenridge, Colorado, USA",
    "Crested Butte, Colorado, USA",
    "Ottawa, Ontario, Canada",
    // 2006
    "Crested Butte, Colorado, USA",
    "Denver, Colorado, USA",
    "Anini Beach, Kauai, Hawaii, USA",
    "Crested Butte, Colorado",
    "Santa Teresa, Costa Rica",
    "San Jose, Costa Rica",
    "Crested Butte, Colorado, USA",
    "Malibu, California, USA",
    "Grand Canyon National Park, USA",
    "Moab, Utah, USA",
    "Saint Paul, Minneapolis, Minnesota, USA",
    "Crested Butte, Colorado, USA",
    "Calgary, Alberta, Canada",
    "Crested Butte, Colorado, USA",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Saint Paul, Minneapolis, Minnesota, USA",
    "Calgary, Alberta, Canada",
    // 2007
    "Houston, Texas, USA",
    "Santa Teresa, Costa Rica",
    "Houston, Texas, USA",
    "Calgary, Alberta, Canada",
    "Fernie, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Calgary, Alberta, Canada", // (B.A. Convocation)
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Napanee, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    // 2008
    "Toronto, Ontario, Canada",
    "Addis Ababa, Ethiopia",
    "Debre Sina, Ethiopia",
    "Debre Birhan, Ethiopia",
    "Ankober, Ethiopia",
    "Debre Sina, Ethiopia",
    "Addis Ababa, Ethiopia",
    "Nazret, Ethiopia",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Victoria, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    // 2009
    "Winnipeg, Manitoba, Canada",
    "Golden, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Montreal, Quebec, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Auckland, New Zealand",
    "Kaitaia, New Zealand",
    "Ahipara, New Zealand",
    "Auckland, New Zealand",
    "Whitianga, New Zealand",
    "Tauranga, New Zealand",
    "Rotorua, New Zealand",
    "Taupo, New Zealand",
    "Palmerston North, New Zealand",
    "Wellington, New Zealand",
    "Picton, New Zealand",
    "Greymouth, New Zealand",
    "Franz Josef, New Zealand",
    "Wanaka, New Zealand",
    "Queenstown, New Zealand",
    "Invercargill, New Zealand",
    "Dunedin, New Zealand",
    "Oamaru, New Zealand",
    "Christchurch, New Zealand",
    "Nelson, New Zealand",
    "Motueka, New Zealand",
    "Abel Tasman National Park, New Zealand",
    "Nelson, New Zealand",
    "Wellington, New Zealand",
    "Palmerston North, New Zealand",
    "National Park, New Zealand", // Tongariro National Park, New Zealand,
    "Hamilton, New Zealand",
    "Auckland, New Zealand",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    // 2010
    "Winnipeg, Manitoba, Canada",
    "Toronto, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Penticton, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Winnipeg, Manitoba, Canada",
    "Churchill, Manitoba, Canada",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    // 2011
    "Clear Lake, Manitoba, Canada",
    "Winnipeg, Manitoba, Canada",
    "Rosthern, Saskatchewan, Canada",
    "Slave Lake, Alberta, Canada",
    "Coleman, Alberta, Canada",
    "Calgary, Alberta, Canada",
    "Slave Lake, Alberta, Canada",
    "Shuswap, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Kamloops, British Columbia, Canada",
    "East Barriere Lake, British Columbia, Canada", // (Mac’s Cabin)",
    "Kamloops, British Columbia, Canada",
    "Calgary, Alberta, Canada",
    "Regina, Saskatchewan, Canada",
    "Winnipeg, Manitoba, Canada",
    "Mazatlan, Mexico",
    "Sayulita, Mexico",
    "Guadalajara, Mexico",
    "Mexico City, Mexico",
    "Tequila, Mexico",
    // 2012
    "Sayulita, Mexico",
    "Mazatlan, Mexico",
    "Winnipeg, Manitoba, Canada",
    "Ottawa, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Vanscoy, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Edmonton, Alberta, Canada",
    "Ottawa, Ontario, Canada",
    "Westport, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Vanscoy, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada", // (Wedding and Music Camp)
    "Saskatoon, Saskatchewan, Canada",
    "Regina, Saskatchewan, Canada",
    "Winnipeg, Manitoba, Canada", // (Nita’s Red Egg Day + March Convocation)
    "Thunder Bay, Ontario, Canada",
    "Sault Ste Marie, Ontario, Canada",
    "Ottawa, Ontario, Canada",
    "Sainte-Agathe-des-Monts",
    "Toronto, Ontario, Canada",
    "Sault Ste Marie, Ontario, Canada",
    "Thunder Bay, Ontario, Canada",
    "Winnipeg, Manitoba, Canada",
    "Regina, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Moose Jaw, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Ottawa, Ontario, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Cardross, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Birch Lake, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Birch Lake, Saskatchewan, Canada",
    "Coleman, Alberta, Canada",
    "Blairmore, Alberta, Canada",
    "Ymir, British Columbia, Canada",
    "Kaslo, British Columbia, Canada",
    "Kamloops, British Columbia, Canada",
    "Vancouver, British Columbia, Canada",
    "Sechelt, British Columbia, Canada",
    "Squamish, British Columbia, Canada",
    "Cache Creek, British Columbia, Canada",
    "Jasper, Alberta, Canada",
    "Edmonton, Alberta, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Turtle Lake, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Lethbridge, Alberta, Canada",
    "Saskatoon, Saskatchewan, Canada ",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Ottawa, Ontario, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Big River, Saskatchewan, Canada",
    "Saskatoon, Saskatchewan, Canada",
    "Kauai, Hawaii",
    "Saskatoon, Saskatchewan, Canada"
  ]
};
